# Generated by Django 4.1.13 on 2023-11-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=150)),
                ('Last_Name', models.CharField(max_length=225)),
                ('Degree', models.CharField(max_length=255)),
                ('Relationship', models.CharField(max_length=255)),
                ('Skin_Color', models.CharField(max_length=255)),
            ],
        ),
    ]
